server:
  port: 9527 #服务端口

spring:
  application:
    name: cloud-gateway9527 #服务名
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1 #路由的ID。没有固定规则，但要求唯一，建议配合服务名使用
          uri: lb://CLOUD-PROVIDER-PAYMENT
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #路由的ID。没有固定规则，但要求唯一，建议配合服务名使用
          uri: lb://CLOUD-PROVIDER-PAYMENT
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/eurekaInfo/** #断言，路径相匹配的进行路由
            - After=2020-03-16T17:40:29.949+08:00[Asia/Shanghai] # 定义该断言什么时间生效,可以通过ZonedDateTime获取时间格式



eureka:
  instance:
#    hostname: cloud-gateway-service
    instance-id: cloud-gateway-service9527
    prefer-ip-address: true # 访问路径可以显示IP地址
  client:
    # 向注册中心注册自己
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true；单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 与 eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
