server:
  port: 8001 #服务端口

spring:
  application:
    name: cloud-provider-hystrix-payment #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径可以显示IP地址
  client:
    # 向注册中心注册自己
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true；单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 与 eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/


devtools:
  restart:
    enabled: true #是否支持热部署
# 开启服务降级
feign:
  hystrix:
    enabled: true